POST http://localhost:3000/SV1/JournalsTable/Insert/BulkAsIs
Content-Type: application/json

[
  {
    "AccountName": "",
    "Date": "",
    "Description": "",
    "Credit": "",
    "Debit": ""
  }
]