POST http://localhost:3000/V5/JournalsTable/SubTable/Insert/WithUuIdAndDT/{RowIndex}/{KeyName}
Content-Type: application/json

{
  "AccountName": "",
  "Date": "",
  "Description": "",
  "Credit": "",
  "Debit": ""
}