POST http://localhost:3000/V2/JournalsTable/SubTable/Insert/AsIs/{RowIndex}/{KeyName}
Content-Type: application/json

{
  "AccountName": "",
  "Date": "",
  "Description": "",
  "Credit": "",
  "Debit": ""
}