POST http://localhost:3000/SV1/JournalsTable/SubTable/Alter/WithPk/{RowPk}/{KeyName}/{pk}
Content-Type: application/json

{
  "AccountName": "",
  "Date": "",
  "Description": "",
  "Credit": "",
  "Debit": ""
}